<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = Carbon::now();
        
        DB::table('cities')->insert([
            ['city_name' => 'Visakhapatnam', 'pin_code' => 530001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vijayawada', 'pin_code' => 520001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Guntur', 'pin_code' => 522001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tirupati', 'pin_code' => 517501, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kakinada', 'pin_code' => 533001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nellore', 'pin_code' => 524001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rajahmundry', 'pin_code' => 533101, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Anantapur', 'pin_code' => 515001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chittoor', 'pin_code' => 517001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kadapa', 'pin_code' => 516001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kurnool', 'pin_code' => 518001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Eluru', 'pin_code' => 534001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ongole', 'pin_code' => 523001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Proddatur', 'pin_code' => 516360, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Srikakulam', 'pin_code' => 532001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tadepalligudem', 'pin_code' => 534101, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nandyal', 'pin_code' => 518501, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vizianagaram', 'pin_code' => 535001, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Macherla', 'pin_code' => 522426, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Narasaraopet', 'pin_code' => 522601, 'state_id' => 1, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            

            ['city_name' => 'Itanagar', 'pin_code' => 791111, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tawang', 'pin_code' => 790104, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ziro', 'pin_code' => 791120, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bomdila', 'pin_code' => 790201, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pasighat', 'pin_code' => 791102, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tezpur', 'pin_code' => 791001, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Naharlagun', 'pin_code' => 791110, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Namsai', 'pin_code' => 792103, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Aalo', 'pin_code' => 791001, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Daporijo', 'pin_code' => 791122, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Yupia', 'pin_code' => 791113, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Khonsa', 'pin_code' => 792101, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Changlang', 'pin_code' => 792120, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Lohit', 'pin_code' => 792001, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Naharalagun', 'pin_code' => 791110, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Lower Dibang Valley', 'pin_code' => 792102, 'state_id' => 2, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Guwahati', 'pin_code' => 781001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dibrugarh', 'pin_code' => 786001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jorhat', 'pin_code' => 785001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Silchar', 'pin_code' => 788001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nagaon', 'pin_code' => 782001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tinsukia', 'pin_code' => 786125, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tezpur', 'pin_code' => 784001, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bongaigaon', 'pin_code' => 783380, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Barpeta', 'pin_code' => 781301, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dhemaji', 'pin_code' => 787057, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Karimganj', 'pin_code' => 788710, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sibsagar', 'pin_code' => 785640, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Goalpara', 'pin_code' => 783121, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sonitpur', 'pin_code' => 784002, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Haflong', 'pin_code' => 788819, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Majuli', 'pin_code' => 785104, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Morigaon', 'pin_code' => 782105, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Darrang', 'pin_code' => 784145, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kamrup', 'pin_code' => 781003, 'state_id' => 3, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Patna', 'pin_code' => 800001, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhagalpur', 'pin_code' => 812001, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Gaya', 'pin_code' => 823001, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Muzaffarpur', 'pin_code' => 842001, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Munger', 'pin_code' => 811201, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Begusarai', 'pin_code' => 851101, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Darbhanga', 'pin_code' => 846004, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sasaram', 'pin_code' => 821115, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chapra', 'pin_code' => 841301, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Arrah', 'pin_code' => 802301, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bihar Sharif', 'pin_code' => 803101, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Katihar', 'pin_code' => 854105, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nalanda', 'pin_code' => 803113, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Purnia', 'pin_code' => 854301, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Lakhisarai', 'pin_code' => 811311, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Buxar', 'pin_code' => 802101, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sitamarhi', 'pin_code' => 843302, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Motihari', 'pin_code' => 845401, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Khagaria', 'pin_code' => 851204, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Samastipur', 'pin_code' => 848101, 'state_id' => 4, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Raipur', 'pin_code' => 492001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bilaspur', 'pin_code' => 495001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Durg', 'pin_code' => 491001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Korba', 'pin_code' => 495677, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Raigarh', 'pin_code' => 496001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhilai', 'pin_code' => 490001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jagdalpur', 'pin_code' => 494001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ambikapur', 'pin_code' => 497001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Raoghat', 'pin_code' => 492104, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mahasamund', 'pin_code' => 493445, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kawardha', 'pin_code' => 491995, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bilaspur', 'pin_code' => 495001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bemetara', 'pin_code' => 491335, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dhamtari', 'pin_code' => 493773, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rajnandgaon', 'pin_code' => 491441, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mungeli', 'pin_code' => 495334, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kanker', 'pin_code' => 494334, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sakti', 'pin_code' => 497001, 'state_id' => 5, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Panaji', 'pin_code' => 403001, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vasco da Gama', 'pin_code' => 403802, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Margao', 'pin_code' => 403601, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mapusa', 'pin_code' => 403507, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ponda', 'pin_code' => 403401, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Quepem', 'pin_code' => 403705, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Curchorem', 'pin_code' => 403706, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bicholim', 'pin_code' => 403504, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Cortalim', 'pin_code' => 403702, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dona Paula', 'pin_code' => 403004, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Baga', 'pin_code' => 403516, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Anjuna', 'pin_code' => 403509, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Calangute', 'pin_code' => 403516, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Aldona', 'pin_code' => 403508, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Siolim', 'pin_code' => 403517, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chicalim', 'pin_code' => 403711, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Cortalim', 'pin_code' => 403702, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Betalbatim', 'pin_code' => 403713, 'state_id' => 6, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Ahmedabad', 'pin_code' => 380001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Surat', 'pin_code' => 395001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vadodara', 'pin_code' => 390001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rajkot', 'pin_code' => 360001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhavnagar', 'pin_code' => 364001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Gandhinagar', 'pin_code' => 382001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jamnagar', 'pin_code' => 361001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Junagadh', 'pin_code' => 362001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nadiad', 'pin_code' => 387001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Anand', 'pin_code' => 388001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vapi', 'pin_code' => 396195, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bharuch', 'pin_code' => 392001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Surendranagar', 'pin_code' => 363001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mehsana', 'pin_code' => 384001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Himmatnagar', 'pin_code' => 383001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Navsari', 'pin_code' => 396445, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Porbandar', 'pin_code' => 360575, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dwarka', 'pin_code' => 361335, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhuj', 'pin_code' => 370001, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kheda', 'pin_code' => 387411, 'state_id' => 7, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Chandigarh', 'pin_code' => 160001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Gurugram', 'pin_code' => 122001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Faridabad', 'pin_code' => 121001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Panipat', 'pin_code' => 132103, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ambala', 'pin_code' => 134001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Karnal', 'pin_code' => 132001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rohtak', 'pin_code' => 124001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sonipat', 'pin_code' => 131001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hisar', 'pin_code' => 125001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Yamunanagar', 'pin_code' => 135001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhiwani', 'pin_code' => 127021, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Fatehabad', 'pin_code' => 125050, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Narnaul', 'pin_code' => 123001, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Palwal', 'pin_code' => 121102, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rewari', 'pin_code' => 123401, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kaithal', 'pin_code' => 136027, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sirsa', 'pin_code' => 125055, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mahendragarh', 'pin_code' => 123029, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jind', 'pin_code' => 126102, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Charkhi Dadri', 'pin_code' => 127306, 'state_id' => 8, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Shimla', 'pin_code' => 171001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Manali', 'pin_code' => 175131, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kullu', 'pin_code' => 175101, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Solan', 'pin_code' => 173212, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kangra', 'pin_code' => 176001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mandi', 'pin_code' => 175001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dharamshala', 'pin_code' => 176215, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bilaspur', 'pin_code' => 174001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nahan', 'pin_code' => 173001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chamba', 'pin_code' => 176310, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Palampur', 'pin_code' => 176061, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hamirpur', 'pin_code' => 177001, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kullu', 'pin_code' => 175101, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Una', 'pin_code' => 174303, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Narkanda', 'pin_code' => 171213, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chail', 'pin_code' => 173217, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rohru', 'pin_code' => 171207, 'state_id' => 9, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Ranchi', 'pin_code' => 834001, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jamshedpur', 'pin_code' => 831001, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dhanbad', 'pin_code' => 826001, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bokaro Steel City', 'pin_code' => 827001, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Deoghar', 'pin_code' => 814112, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hazaribagh', 'pin_code' => 825301, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Giridih', 'pin_code' => 815301, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dumka', 'pin_code' => 814101, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chaibasa', 'pin_code' => 833201, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jamtara', 'pin_code' => 815351, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Latehar', 'pin_code' => 829206, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ramgarh', 'pin_code' => 829122, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Koderma', 'pin_code' => 825410, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Palamu', 'pin_code' => 822101, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Simdega', 'pin_code' => 835223, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ranchi', 'pin_code' => 834001, 'state_id' => 10, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Bengaluru', 'pin_code' => 560001, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mysuru', 'pin_code' => 570001, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mangalore', 'pin_code' => 575001, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hubballi', 'pin_code' => 580020, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Belagavi', 'pin_code' => 590001, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Davangere', 'pin_code' => 577001, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Shimoga', 'pin_code' => 577201, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tumakuru', 'pin_code' => 572101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Raichur', 'pin_code' => 584101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hassan', 'pin_code' => 573201, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ballari', 'pin_code' => 583101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bidar', 'pin_code' => 585401, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bijapur', 'pin_code' => 586101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chikkamagaluru', 'pin_code' => 577101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Udupi', 'pin_code' => 576101, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Karwar', 'pin_code' => 581301, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Haveri', 'pin_code' => 581110, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chitradurga', 'pin_code' => 577501, 'state_id' => 11, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Thiruvananthapuram', 'pin_code' => 695001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kochi', 'pin_code' => 682001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kozhikode', 'pin_code' => 673001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Malappuram', 'pin_code' => 676505, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Thrissur', 'pin_code' => 680001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kollam', 'pin_code' => 691001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Alappuzha', 'pin_code' => 688001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Palakkad', 'pin_code' => 678001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kannur', 'pin_code' => 670001, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Wayanad', 'pin_code' => 673591, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Idukki', 'pin_code' => 685602, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pathanamthitta', 'pin_code' => 689645, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kasargod', 'pin_code' => 671121, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vatakara', 'pin_code' => 673101, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ponnani', 'pin_code' => 679577, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Changanassery', 'pin_code' => 686101, 'state_id' => 12, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Bhopal', 'pin_code' => 462001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Indore', 'pin_code' => 452001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Gwalior', 'pin_code' => 474001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jabalpur', 'pin_code' => 482001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ujjain', 'pin_code' => 456001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Khandwa', 'pin_code' => 450001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Satna', 'pin_code' => 485001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rewa', 'pin_code' => 486001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sagar', 'pin_code' => 470001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dewas', 'pin_code' => 455001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mandsaur', 'pin_code' => 458001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chhindwara', 'pin_code' => 480001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Burhanpur', 'pin_code' => 450331, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Katni', 'pin_code' => 483501, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mandla', 'pin_code' => 481661, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tikamgarh', 'pin_code' => 472001, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Shivpuri', 'pin_code' => 473551, 'state_id' => 13, 'created_at' => $timestamp, 'updated_at' => $timestamp],
           
            ['city_name' => 'Mumbai', 'pin_code' => 400001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pune', 'pin_code' => 411001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nagpur', 'pin_code' => 440001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nashik', 'pin_code' => 422001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Thane', 'pin_code' => 400601, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Aurangabad', 'pin_code' => 431001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kolhapur', 'pin_code' => 416001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Solapur', 'pin_code' => 413001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jalgaon', 'pin_code' => 425001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Satara', 'pin_code' => 415001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ratnagiri', 'pin_code' => 415612, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chandrapur', 'pin_code' => 442401, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Akola', 'pin_code' => 444001, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhiwandi', 'pin_code' => 421302, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vasai-Virar', 'pin_code' => 401303, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dombivli', 'pin_code' => 421201, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Palghar', 'pin_code' => 401404, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Latur', 'pin_code' => 413512, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Parbhani', 'pin_code' => 431401, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Beed', 'pin_code' => 431122, 'state_id' => 14, 'created_at' => $timestamp, 'updated_at' => $timestamp],



            ['city_name' => 'Imphal', 'pin_code' => 795001, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Thoubal', 'pin_code' => 795138, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kakching', 'pin_code' => 795103, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Churachandpur', 'pin_code' => 795128, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bishnupur', 'pin_code' => 795126, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ukhrul', 'pin_code' => 795142, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Senapati', 'pin_code' => 795106, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tamenglong', 'pin_code' => 795141, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kangpokpi', 'pin_code' => 795114, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chandel', 'pin_code' => 795127, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Moreh', 'pin_code' => 795131, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jiribam', 'pin_code' => 795116, 'state_id' => 15, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Shillong', 'pin_code' => 793001, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tura', 'pin_code' => 794001, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jowai', 'pin_code' => 793150, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nongstoin', 'pin_code' => 793119, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Williamnagar', 'pin_code' => 794111, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Baghmara', 'pin_code' => 794102, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mawkyrwat', 'pin_code' => 793114, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nongpoh', 'pin_code' => 793102, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Resubelpara', 'pin_code' => 794115, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mawphlang', 'pin_code' => 793111, 'state_id' => 16, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Aizawl', 'pin_code' => 796001, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Lunglei', 'pin_code' => 796701, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kolasib', 'pin_code' => 796081, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Champhai', 'pin_code' => 796321, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Serchhip', 'pin_code' => 796181, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mamit', 'pin_code' => 796441, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Siaha', 'pin_code' => 796901, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hnahthial', 'pin_code' => 796470, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Lungdar', 'pin_code' => 796477, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tlabung', 'pin_code' => 796454, 'state_id' => 17, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Kohima', 'pin_code' => 797001, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dimapur', 'pin_code' => 797112, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mokokchung', 'pin_code' => 798601, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Wokha', 'pin_code' => 797111, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Zunheboto', 'pin_code' => 798620, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Phek', 'pin_code' => 797106, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tseminyu', 'pin_code' => 797109, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chümoukedima', 'pin_code' => 797103, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kiphire', 'pin_code' => 797101, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Longleng', 'pin_code' => 798615, 'state_id' => 18, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Bhubaneswar', 'pin_code' => 751001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Cuttack', 'pin_code' => 753001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rourkela', 'pin_code' => 769001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sambalpur', 'pin_code' => 768001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Berhampur', 'pin_code' => 760001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Balasore', 'pin_code' => 756001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kendrapara', 'pin_code' => 754211, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Angul', 'pin_code' => 759122, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dhenkanal', 'pin_code' => 759001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jeypore', 'pin_code' => 764001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Balangir', 'pin_code' => 767001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Puri', 'pin_code' => 752001, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Koraput', 'pin_code' => 764020, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Malkangiri', 'pin_code' => 764047, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nayagarh', 'pin_code' => 752070, 'state_id' => 19, 'created_at' => $timestamp, 'updated_at' => $timestamp],



            ['city_name' => 'Chandigarh', 'pin_code' => 160001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Amritsar', 'pin_code' => 143001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ludhiana', 'pin_code' => 141001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jalandhar', 'pin_code' => 144001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Patiala', 'pin_code' => 147001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bathinda', 'pin_code' => 151001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mohali', 'pin_code' => 160071, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Hoshiarpur', 'pin_code' => 146001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Firozpur', 'pin_code' => 152002, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ropar', 'pin_code' => 140001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kapurthala', 'pin_code' => 144205, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Moga', 'pin_code' => 142001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Barnala', 'pin_code' => 148101, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sangrur', 'pin_code' => 148001, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Faridkot', 'pin_code' => 151203, 'state_id' => 20, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Jaipur', 'pin_code' => 302001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Udaipur', 'pin_code' => 313001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jodhpur', 'pin_code' => 342001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kota', 'pin_code' => 324001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ajmer', 'pin_code' => 305001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bikaner', 'pin_code' => 334001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Alwar', 'pin_code' => 301001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chittorgarh', 'pin_code' => 312001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sri Ganganagar', 'pin_code' => 335001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tonk', 'pin_code' => 304001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pali', 'pin_code' => 306401, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jalore', 'pin_code' => 343001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sikar', 'pin_code' => 332001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Barmer', 'pin_code' => 344001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nagaur', 'pin_code' => 341001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bundi', 'pin_code' => 323001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jaisalmer', 'pin_code' => 345001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sawai Madhopur', 'pin_code' => 322001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhilwara', 'pin_code' => 311001, 'state_id' => 21, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Gangtok', 'pin_code' => 737101, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Namchi', 'pin_code' => 737126, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mangan', 'pin_code' => 737113, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Rangpo', 'pin_code' => 737132, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jorethang', 'pin_code' => 737121, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pakyong', 'pin_code' => 737106, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ravangla', 'pin_code' => 737139, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Geyzing', 'pin_code' => 737111, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Daramdin', 'pin_code' => 737113, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Yuksom', 'pin_code' => 737117, 'state_id' => 22, 'created_at' => $timestamp, 'updated_at' => $timestamp],

            ['city_name' => 'Chennai', 'pin_code' => 600001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Coimbatore', 'pin_code' => 641001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Madurai', 'pin_code' => 625001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tiruchirappalli', 'pin_code' => 620001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Salem', 'pin_code' => 636001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Erode', 'pin_code' => 638001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tirunelveli', 'pin_code' => 627001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Vellore', 'pin_code' => 632001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Thanjavur', 'pin_code' => 613001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Chidambaram', 'pin_code' => 608001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dindigul', 'pin_code' => 624001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nagercoil', 'pin_code' => 629001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dharmapuri', 'pin_code' => 636701, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kanchipuram', 'pin_code' => 631501, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tirupur', 'pin_code' => 641601, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Cuddalore', 'pin_code' => 607001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Karur', 'pin_code' => 639001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Pudukkottai', 'pin_code' => 622001, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ariyalur', 'pin_code' => 621701, 'state_id' => 23, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Hyderabad', 'pin_code' => 500001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Warangal', 'pin_code' => 506001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Khammam', 'pin_code' => 507001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nizamabad', 'pin_code' => 503001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Karimnagar', 'pin_code' => 505001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ramagundam', 'pin_code' => 505208, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Adilabad', 'pin_code' => 504001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mahabubnagar', 'pin_code' => 509001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Nalgonda', 'pin_code' => 508001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Medak', 'pin_code' => 502001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sangareddy', 'pin_code' => 502001, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jagtial', 'pin_code' => 505327, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Peddapalli', 'pin_code' => 505172, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mahabubabad', 'pin_code' => 506101, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Medchal', 'pin_code' => 501401, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Bhongir', 'pin_code' => 508116, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Zaheerabad', 'pin_code' => 502220, 'state_id' => 24, 'created_at' => $timestamp, 'updated_at' => $timestamp],


            ['city_name' => 'Agartala', 'pin_code' => 799001, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Udaipur', 'pin_code' => 799103, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Amarpur', 'pin_code' => 799101, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Kailashahar', 'pin_code' => 799277, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Dharmanagar', 'pin_code' => 799250, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Belonia', 'pin_code' => 799155, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sabroom', 'pin_code' => 799143, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Sonamura', 'pin_code' => 799131, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Jirania', 'pin_code' => 799045, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Khowai', 'pin_code' => 799203, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Radhakishorepur', 'pin_code' => 799114, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Mohanpur', 'pin_code' => 799205, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Boxanagar', 'pin_code' => 799108, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Ranirbazar', 'pin_code' => 799042, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['city_name' => 'Tuilu', 'pin_code' => 799115, 'state_id' => 25, 'created_at' => $timestamp, 'updated_at' => $timestamp],

        ]);
    }
}
